/*
 * This source file was generated by the Gradle 'init' task
 */
package org.console;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        String workingDirectory = System.getProperty("user.dir");

        CSVReader reader = new CSVReader();
        reader.readFile(workingDirectory + "/src/main/resources/sample-data.csv");
    }
}
